<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.3</version>
        <relativePath/>
    </parent>

    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>${version}</version>
    <description>${projectChineseName}</description>

    <properties>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok.version>1.18.36</lombok.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>

        <wheel.version>3.5.50</wheel.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${groupId}</groupId>
                <artifactId>${rootArtifactId}</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>${groupId}</groupId>
            <artifactId>${rootArtifactId}-api</artifactId>
        </dependency>

        <!-- 如果需要调用其它微服务，请引用此包，否则不需要 -->
        <dependency>
            <groupId>com.github.rebue.sbs</groupId>
            <artifactId>feign-spring-boot-starter</artifactId>
        </dependency>

        <!-- smart-doc推送api信息到torna需要打开注释 -->
        <!--        <dependency>-->
        <!--            <groupId>com.github.rebue.wheel</groupId>-->
        <!--            <artifactId>wheel-api</artifactId>-->
        <!--            <classifier>sources</classifier>-->
        <!--            <version>${wheel.version}</version>-->
        <!--        </dependency>-->

        <dependency>
            <groupId>com.github.rebue.robotech</groupId>
            <artifactId>robotech-bll</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.rebue.sbs</groupId>
            <artifactId>sb-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.rebue.sbs</groupId>
            <artifactId>sc-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postgis</groupId>
            <artifactId>postgis-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.rebue.wheel</groupId>
            <artifactId>wheel-net</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- smart-doc如果项目依赖其他内部公共模块和二方包, 则依赖包需要配置源码打包 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- smart-doc -->
            <plugin>
                <groupId>com.ly.smart-doc</groupId>
                <artifactId>smart-doc-maven-plugin</artifactId>
                <version>3.0.3</version>
                <configuration>
                    <!-- 指定生成文档的使用的配置文件 -->
                    <configFile>${basedir}/src/main/resources/config/smart-doc.json</configFile>
                    <!--                    <includes>-->
                    <!--                        <include>com.github.rebue.wheel:*</include>-->
                    <!--                    </includes>-->
                </configuration>
            </plugin>

            <!-- native打包需要 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- 排除打包 src/main/resources 下的所有文件 -->
                        <exclude>config/**</exclude>
                        <exclude>db/**</exclude>
                        <exclude>META-INF/**</exclude>
                        <exclude>security/**</exclude>
                        <exclude>static/**</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <!-- Maven 编译插件，提供给 Lombok 和 MapStruct 使用 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <!-- MapStruct 注解处理器 -->
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <!-- Lombok 注解处理器 -->
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <!-- MapStruct 和 Lombok 注解绑定处理器 -->
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>0.10.1</version>
                <configuration>
                    <mainClass>${groupId}.${projectNameCapitalise}Application</mainClass>
                    <buildArgs>
                        <!-- 建立独立镜像，不成功则报告失败 -->
                        <buildArg>--no-fallback</buildArg>
                        <!-- 开启实验性的功能 -->
                        <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                        <!-- 列出要打包的资源 -->
                        <buildArg>-H:ExcludeResources=config/*</buildArg>>
                        <!-- 指定native-image配置文件的目录(此目录由maven编译gen-native-image-config生成) -->
                        <buildArg>-H:ConfigurationFileDirectories=src/main/resources/META-INF/native-image/</buildArg>
                        <!-- 级别设置为3，打包时输出包含的资源文件 -->
                        <buildArg>-H:Log=registerResource:3</buildArg>
                    </buildArgs>
                    <!-- native-image编译时输出详细的日志 -->
                    <verbose>true</verbose>
                    <!-- 生成调试信息 -->
                    <debug>true</debug>
                    <!-- 快速编译 -->
                    <quickBuild>true</quickBuild>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <!-- 生成native-image的配置文件需要 -->
            <!-- 因为是利用test插件生成，所以不能skip test -->
            <!-- maven命令使用test，并最好加上 '-Dtest=CodgenApplicationTests#testMain' 参数限定测试的方法 -->
            <id>gen-native-image-config</id>
            <build>
                <plugins>
                    <!-- 执行测试用例的插件 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin.version}</version>
                        <configuration>
                            <argLine>
                                -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image
                            </argLine>
                            <includes>
                                <include>**/*Tests.java</include>
                            </includes>
                            <!-- 因为native-image-agent根据测试生成反射的配置文件，所以不能跳过测试 -->
                            <skip>false</skip>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
