package bindings;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.github.codgen.core.drools.fact.BindingsFact;


/**
 * 默认绑定变量到模板中
 */
rule bindings_default
    agenda-group "bindings" // 议程分组
    no-loop true            // 防止死循环(当规则通过update之类的函数修改了Fact对象时，可能使当前规则再次被激活从而导致死循环)
    lock-on-active true     // 限制当前规则只会被执行一次(包括当前规则的重复执行不是本身触发的)
    salience -1             // 执行的优先级(值越大优先级越高，可以为负数，不设置默认为0)
when
    $bindingsFact: BindingsFact()
then
    System.out.println("--------- 绑定全局变量 ---------");
    for (Map.Entry<String, ?> globalVariable : $bindingsFact.getGlobalVariableMap().entrySet()) {
        String key = globalVariable.getKey();
        Object value = globalVariable.getValue();
        System.out.println(key + ": " + value);
        $bindingsFact.getTemplateInfo().getPathTemplate().binding(key, value);
        $bindingsFact.getTemplateInfo().getContentTemplate().binding(key, value);
    }
    System.out.println("-----------------------------");
    update($bindingsFact);
end