package render;

import java.util.Map;
import java.util.HashMap;
import io.github.codgen.core.drools.fact.RenderFact
import java.util.List;
import io.github.codgen.core.FileInfo
import io.github.codgen.core.FileInfo;

/**
 * 默认渲染
 */
rule render_default
    agenda-group "render"   // 议程分组
    no-loop true            // 防止死循环(当规则通过update之类的函数修改了Fact对象时，可能使当前规则再次被激活从而导致死循环)
    lock-on-active true     // 限制当前规则只会被执行一次(包括当前规则的重复执行不是本身触发的)
    salience -1             // 执行的优先级(值越大优先级越高，可以为负数，不设置默认为0)
when
    $renderFact: RenderFact()
then
    String path = $renderFact.getTemplateInfo().getPathTemplate().render();
    System.out.println("Default render: " + path);
    $renderFact.getOutFileInfos().add(FileInfo.builder()
        .path(path)
        .content($renderFact.getTemplateInfo().getContentTemplate().render())
        .build());
    update($renderFact);
end