<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>${version}</version>
    <packaging>pom</packaging>
    <description>${projectDescription}</description>

    <modules>
        <module>${rootArtifactId}-gen</module>
        <module>${rootArtifactId}-api</module>
        <module>${rootArtifactId}-svr</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <codgen.version>1.2.37</codgen.version>
        <mbgx.version>3.8.64</mbgx.version>
        <wheel.version>3.8.64</wheel.version>
        <robotech.version>3.8.64</robotech.version>
        <sbs.version>3.8.64</sbs.version>
        <adm.version>1.0.0</adm.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${groupId}</groupId>
                <artifactId>${rootArtifactId}-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- 权限拦截 -->
            <dependency>
                <groupId>rebue.adm</groupId>
                <artifactId>adm-auth</artifactId>
                <version>${adm.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.rebue.wheel</groupId>
                <artifactId>wheel</artifactId>
                <version>${wheel.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.github.codgen</groupId>
                <artifactId>codgen-cmd</artifactId>
                <version>${codgen.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.codgen</groupId>
                <artifactId>codgen-java</artifactId>
                <version>${codgen.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.rebue.mbgx</groupId>
                <artifactId>mbgx</artifactId>
                <version>${mbgx.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.rebue.robotech</groupId>
                <artifactId>robotech</artifactId>
                <version>${robotech.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.github.rebue.sbs</groupId>
                <artifactId>sbs</artifactId>
                <version>${sbs.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <!-- 打包时发布源码(smart-doc可以获取参数信息) -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
